-- HPC Alumni Association - MySQL schema (Express + Aiven MySQL)
-- Notes:
-- - IDs are CHAR(36) UUID strings generated by the backend.
-- - JSON columns store structured content (landing_content, live_result_settings, social_links, etc.).

CREATE DATABASE IF NOT EXISTS `defaultdb` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `defaultdb`;

-- ----------------------------
-- Auth (users + verification)
-- ----------------------------

CREATE TABLE IF NOT EXISTS `users` (
  `id` CHAR(36) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `email_verified` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `email_verification_tokens` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `used_at` DATETIME NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_verification_tokens_token_unique` (`token`),
  KEY `email_verification_tokens_user_id_idx` (`user_id`),
  CONSTRAINT `email_verification_tokens_user_fk`
    FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `google_identities` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `google_sub` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `google_identities_google_sub_unique` (`google_sub`),
  KEY `google_identities_user_id_idx` (`user_id`),
  CONSTRAINT `google_identities_user_fk`
    FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB;

-- ----------------------------
-- Profiles + roles
-- ----------------------------

CREATE TABLE IF NOT EXISTS `profiles` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `phone` TEXT NULL,
  `batch` TEXT NULL,
  `roll` TEXT NULL,
  `registration_number` TEXT NULL,
  `gender` TEXT NULL,
  `blood_group` TEXT NULL,
  `department` TEXT NULL,
  `faculty` VARCHAR(32) NULL,
  `session` TEXT NULL,
  `passing_year` TEXT NULL,
  `college_name` TEXT NULL,
  `profession` TEXT NULL,
  `company` TEXT NULL,
  `university` TEXT NULL,
  `job_status` TEXT NULL,
  `job_title` TEXT NULL,
  `address` TEXT NULL,
  `bio` TEXT NULL,
  `additional_info` TEXT NULL,
  `photo` TEXT NULL,
  `social_links` JSON NULL,
  `role_verified_email` BOOLEAN NOT NULL DEFAULT FALSE,
  `verified` BOOLEAN NOT NULL DEFAULT FALSE,
  `approved` BOOLEAN NOT NULL DEFAULT FALSE,
  `blocked` BOOLEAN NOT NULL DEFAULT FALSE,
  `profile_pending` BOOLEAN NOT NULL DEFAULT FALSE,
  `profile_review_note` TEXT NULL,
  `directory_visible` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `profiles_user_fk`
    FOREIGN KEY (`id`) REFERENCES `users` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `user_roles` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `role` ENUM('admin', 'user') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_roles_user_id_role_unique` (`user_id`, `role`),
  KEY `user_roles_user_id_idx` (`user_id`),
  CONSTRAINT `user_roles_user_fk`
    FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB;

-- ----------------------------
-- Landing content
-- ----------------------------

CREATE TABLE IF NOT EXISTS `landing_content` (
  `id` CHAR(36) NOT NULL,
  `section_key` VARCHAR(100) NOT NULL,
  `content` JSON NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` CHAR(36) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `landing_content_section_key_unique` (`section_key`),
  KEY `landing_content_updated_by_idx` (`updated_by`),
  CONSTRAINT `landing_content_updated_by_fk`
    FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`)
    ON DELETE SET NULL
) ENGINE=InnoDB;

-- ----------------------------
-- Committee
-- ----------------------------

CREATE TABLE IF NOT EXISTS `committee_terms` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `status` ENUM('draft', 'published') NOT NULL DEFAULT 'draft',
  `is_current` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `committee_terms_status_idx` (`status`),
  KEY `committee_terms_current_idx` (`is_current`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `committee_posts` (
  `id` CHAR(36) NOT NULL,
  `term_id` CHAR(36) NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `allows_multiple` TINYINT(1) NOT NULL DEFAULT 1,
  `is_highlight` TINYINT(1) NOT NULL DEFAULT 0,
  `display_order` INT NOT NULL DEFAULT 0,
  `board_section` VARCHAR(40) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `committee_posts_term_order_idx` (`term_id`, `display_order`),
  CONSTRAINT `committee_posts_term_fk_schema`
    FOREIGN KEY (`term_id`) REFERENCES `committee_terms` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `committee_members` (
  `id` CHAR(36) NOT NULL,
  `term_id` CHAR(36) NULL,
  `post_id` CHAR(36) NULL,
  `name` TEXT NOT NULL,
  `designation` TEXT NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `batch` TEXT NULL,
  `alumni_id` VARCHAR(100) NULL,
  `phone` VARCHAR(100) NULL,
  `email` VARCHAR(255) NULL,
  `candidate_number` VARCHAR(100) NULL,
  `college_name` TEXT NULL,
  `institution` TEXT NULL,
  `job_status` TEXT NULL,
  `profession` TEXT NULL,
  `location` TEXT NULL,
  `expertise` TEXT NULL,
  `about` TEXT NULL,
  `wishing_message` TEXT NULL,
  `winner_about` TEXT NULL,
  `facebook_url` TEXT NULL,
  `instagram_url` TEXT NULL,
  `linkedin_url` TEXT NULL,
  `photo_url` TEXT NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  `is_active` BOOLEAN NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `committee_members_term_idx` (`term_id`),
  KEY `committee_members_post_idx` (`post_id`),
  CONSTRAINT `committee_members_term_fk_schema`
    FOREIGN KEY (`term_id`) REFERENCES `committee_terms` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `committee_members_post_fk_schema`
    FOREIGN KEY (`post_id`) REFERENCES `committee_posts` (`id`)
    ON DELETE SET NULL
) ENGINE=InnoDB;

-- ----------------------------
-- Dropdown options for executive committee
-- ----------------------------
CREATE TABLE IF NOT EXISTS `profession_options` (
  `id` CHAR(36) NOT NULL,
  `value` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `profession_options_value_unique` (`value`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `job_status_options` (
  `id` CHAR(36) NOT NULL,
  `value` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `job_status_options_value_unique` (`value`)
) ENGINE=InnoDB;

-- Seed common job statuses (if not present)
INSERT INTO `job_status_options` (`id`, `value`)
SELECT UUID(), 'Student' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `job_status_options` WHERE `value` = 'Student' LIMIT 1);
INSERT INTO `job_status_options` (`id`, `value`)
SELECT UUID(), 'Job Holder' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `job_status_options` WHERE `value` = 'Job Holder' LIMIT 1);
INSERT INTO `job_status_options` (`id`, `value`)
SELECT UUID(), 'Business' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `job_status_options` WHERE `value` = 'Business' LIMIT 1);
INSERT INTO `job_status_options` (`id`, `value`)
SELECT UUID(), 'Freelancer' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `job_status_options` WHERE `value` = 'Freelancer' LIMIT 1);
INSERT INTO `job_status_options` (`id`, `value`)
SELECT UUID(), 'Unemployed' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `job_status_options` WHERE `value` = 'Unemployed' LIMIT 1);

-- ----------------------------
-- Achievements + settings
-- ----------------------------

CREATE TABLE IF NOT EXISTS `achievements` (
  `id` CHAR(36) NOT NULL,
  `name` TEXT NOT NULL,
  `batch` TEXT NULL,
  `photo_url` TEXT NULL,
  `achievement_title` TEXT NOT NULL,
  `institution` TEXT NULL,
  `message` TEXT NULL,
  `tag` TEXT NULL,
  `location` TEXT NULL,
  `achievement_date` DATETIME NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `display_order` INT NULL DEFAULT 0,
  `is_active` BOOLEAN NULL DEFAULT TRUE,
  `is_pinned` BOOLEAN NULL DEFAULT FALSE,
  `banner_theme` VARCHAR(32) NULL DEFAULT 'default',
  `banner_photo_batch_text` TEXT NULL,
  `banner_photo_tagline` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `achievement_settings` (
  `id` CHAR(36) NOT NULL,
  `banner_enabled` BOOLEAN NULL DEFAULT TRUE,
  `slide_duration` INT NULL DEFAULT 4,
  `max_display_count` INT NULL,
  `banner_theme` VARCHAR(32) NULL DEFAULT 'default',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

-- Default banner settings row (API also auto-creates if missing)
INSERT INTO `achievement_settings` (`id`, `banner_enabled`, `slide_duration`, `max_display_count`, `banner_theme`)
SELECT UUID(), 1, 4, NULL, 'default' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `achievement_settings` LIMIT 1);

-- ----------------------------
-- Memories
-- ----------------------------

CREATE TABLE IF NOT EXISTS `memories` (
  `id` CHAR(36) NOT NULL,
  `title` TEXT NOT NULL,
  `category` VARCHAR(100) NOT NULL DEFAULT 'General',
  `description` TEXT NULL,
  `photo_url` TEXT NULL,
  `published` BOOLEAN NULL DEFAULT FALSE,
  `display_order` INT NULL DEFAULT 0,
  `event_date` DATE NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

-- ----------------------------
-- Documents
-- ----------------------------

CREATE TABLE IF NOT EXISTS `documents` (
  `id` CHAR(36) NOT NULL,
  `category` TEXT NOT NULL,
  `title` TEXT NOT NULL,
  `description` TEXT NULL,
  `file_url` MEDIUMTEXT NOT NULL,
  `file_name` TEXT NULL,
  `file_type` TEXT NULL,
  `file_size` BIGINT NULL,
  `visibility` VARCHAR(50) NOT NULL DEFAULT 'public',
  `published` BOOLEAN NOT NULL DEFAULT FALSE,
  `pinned` BOOLEAN NULL DEFAULT FALSE,
  `uploaded_by` CHAR(36) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `documents_uploaded_by_idx` (`uploaded_by`),
  CONSTRAINT `documents_uploaded_by_fk`
    FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`)
    ON DELETE SET NULL
) ENGINE=InnoDB;

-- ----------------------------
-- Notices
-- ----------------------------

CREATE TABLE IF NOT EXISTS `notices` (
  `id` CHAR(36) NOT NULL,
  `notice_type` TEXT NULL,
  `title` TEXT NOT NULL,
  `content` TEXT NULL,
  `summary` TEXT NULL,
  `published` BOOLEAN NULL DEFAULT FALSE,
  `pinned` BOOLEAN NULL DEFAULT FALSE,
  `urgent` BOOLEAN NULL DEFAULT FALSE,
  `show_top_bar` BOOLEAN NULL DEFAULT FALSE,
  `audience` VARCHAR(50) NULL,
  `expiry_date` DATETIME NULL,
  `external_link` TEXT NULL,
  `linked_document_id` CHAR(36) NULL,
  `attachment_url` MEDIUMTEXT NULL,
  `attachment_type` TEXT NULL,
  `image_url` MEDIUMTEXT NULL,
  `created_by` CHAR(36) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `notices_created_by_idx` (`created_by`),
  CONSTRAINT `notices_created_by_fk`
    FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
    ON DELETE SET NULL
) ENGINE=InnoDB;

-- ----------------------------
-- Events
-- ----------------------------

CREATE TABLE IF NOT EXISTS `events` (
  `id` CHAR(36) NOT NULL,
  `title` TEXT NOT NULL,
  `description` TEXT NULL,
  `event_date` DATE NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `location` TEXT NULL,
  `online_link` TEXT NULL,
  `form_link` TEXT NULL,
  `banner_url` MEDIUMTEXT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'draft',
  `published` BOOLEAN NULL DEFAULT FALSE,
  `created_by` CHAR(36) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `events_created_by_idx` (`created_by`),
  CONSTRAINT `events_created_by_fk`
    FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
    ON DELETE SET NULL
) ENGINE=InnoDB;

-- ----------------------------
-- Elections (admin + user vote)
-- ----------------------------

CREATE TABLE IF NOT EXISTS `elections` (
  `id` CHAR(36) NOT NULL,
  `title` TEXT NOT NULL,
  `description` TEXT NULL,
  `term_year` TEXT NULL,
  `election_type` VARCHAR(30) NOT NULL DEFAULT 'general',
  `status` VARCHAR(20) NOT NULL DEFAULT 'draft',
  `application_start` DATETIME NULL,
  `application_end` DATETIME NULL,
  `voting_start` DATETIME NULL,
  `voting_end` DATETIME NULL,
  `result_visibility` VARCHAR(50) NOT NULL DEFAULT 'hidden',
  `live_result_settings` JSON NULL,
  `created_by` CHAR(36) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `elections_created_by_idx` (`created_by`),
  CONSTRAINT `elections_created_by_fk`
    FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
    ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `election_posts` (
  `id` CHAR(36) NOT NULL,
  `election_id` CHAR(36) NOT NULL,
  `post_name` TEXT NOT NULL,
  `display_order` INT NULL DEFAULT 0,
  `max_candidates` INT NULL,
  `winners_count` INT NULL DEFAULT 1,
  `is_open_for_application` BOOLEAN NULL DEFAULT TRUE,
  `admin_nomination_only` BOOLEAN NULL DEFAULT FALSE,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `election_posts_election_id_idx` (`election_id`),
  CONSTRAINT `election_posts_election_fk`
    FOREIGN KEY (`election_id`) REFERENCES `elections` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `candidates` (
  `id` CHAR(36) NOT NULL,
  `election_id` CHAR(36) NOT NULL,
  `post_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NULL,
  `name` TEXT NOT NULL,
  `batch` TEXT NULL,
  `photo_url` MEDIUMTEXT NULL,
  `manifesto` TEXT NULL,
  `candidate_number` INT NULL,
  `phone` TEXT NULL,
  `email` TEXT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `is_manual` BOOLEAN NULL DEFAULT FALSE,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `candidates_election_id_idx` (`election_id`),
  KEY `candidates_post_id_idx` (`post_id`),
  CONSTRAINT `candidates_election_fk`
    FOREIGN KEY (`election_id`) REFERENCES `elections` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `candidates_post_fk`
    FOREIGN KEY (`post_id`) REFERENCES `election_posts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `candidates_user_fk`
    FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
    ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `votes` (
  `id` CHAR(36) NOT NULL,
  `election_id` CHAR(36) NOT NULL,
  `post_id` CHAR(36) NOT NULL,
  `candidate_id` CHAR(36) NOT NULL,
  `voter_id` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `votes_unique_election_post_voter` (`election_id`, `post_id`, `voter_id`),
  KEY `votes_candidate_id_idx` (`candidate_id`),
  CONSTRAINT `votes_election_fk`
    FOREIGN KEY (`election_id`) REFERENCES `elections` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `votes_post_fk`
    FOREIGN KEY (`post_id`) REFERENCES `election_posts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `votes_candidate_fk`
    FOREIGN KEY (`candidate_id`) REFERENCES `candidates` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `election_winners` (
  `id` CHAR(36) NOT NULL,
  `election_id` CHAR(36) NOT NULL,
  `post_id` CHAR(36) NOT NULL,
  `candidate_id` CHAR(36) NOT NULL,
  `congratulation_message` TEXT NULL,
  `vote_count` INT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `election_winners_election_id_idx` (`election_id`),
  CONSTRAINT `election_winners_election_fk`
    FOREIGN KEY (`election_id`) REFERENCES `elections` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `election_winners_post_fk`
    FOREIGN KEY (`post_id`) REFERENCES `election_posts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `election_winners_candidate_fk`
    FOREIGN KEY (`candidate_id`) REFERENCES `candidates` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB;

